Causes exception: warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]       Unhandled exception rendering component: table.getElementsByTagName is not a function makeSortable@http://localhost:5248/sorttable.js:44:15